```mermaid
---
title: Customer Profile
---
mindmap
CustomerProfile(CustomerProfile)
    Favorite
    SeenProduct(SeenProduct)
    ManagePersonalOrder
        BoughtOrder(BoughtOrder)
        ProcessedOrder(ProcessedOrder)
        CanceledOrder(CanceledOrder)
    ManagePersonalProfile

```