```mermaid
---
title: Product Grid
---
mindmap
ProductGrid(ProductGrid)
    Search
        ByName(ByName)
        ByTag(ByTag)
    Filter
        ByCategory(ByCategory)
        ByPrice(ByPrice)
        BySpecification(BySpecification)
        ByBrand(ByBrand)
        ByTag(ByTag)
            BestSeller(BestSeller)
            New(New)
    Sort
        ByPrice(ByPrice)
        ByName(ByName)

```