export const CURRENT_TOKEN = 'CURRENT_TOKEN';

export const READ_ALL_ACCOUNTS = 'READ_ALL_ACCOUNTS';
export const READ_ALL_PRODUCTS = 'READ_ALL_PRODUCTS';
export const READ_ALL_TAGS = 'READ_ALL_TAGS';
export const READ_ALL_CATEGORIES = 'READ_ALL_CATEGORIES';
export const READ_ALL_BRANDS = 'READ_ALL_BRANDS';
export const READ_ALL_VOUCHERS = 'READ_ALL_VOUCHERS';
export const READ_ALL_SPECIFICATION = 'READ_ALL_SPECIFICATION';
export const READ_ALL_CAROUSEL = 'READ_ALL_CAROUSEL';
export const READ_ALL_ORDERS = 'READ_ALL_ORDERS';
export const READ_ALL_REVIEWS = 'READ_ALL_REVIEWS';
export const READ_ALL_ADDRESSES = 'READ_ALL_ADDRESSES';
export const READ_ALL_CARTS = 'READ_ALL_CARTS';
export const READ_ALL_WISHLISTS = 'READ_ALL_WISHLISTS';
