export const READ_ALL_ACCOUNTS = 'READ_ALL_ACCOUNTS';
export const READ_ALL_PRODUCTS = 'READ_ALL_PRODUCTS';
export const READ_ALL_TAGS = 'READ_ALL_TAGS';
export const READ_ALL_CATEGORIES = 'READ_ALL_CATEGORIES';
export const READ_ALL_BRANDS = 'READ_ALL_BRANDS';
export const READ_ALL_VOUCHERS = 'READ_ALL_VOUCHERS';
export const READ_ALL_SPECIFICATION = 'READ_ALL_SPECIFICATION';
