// queryKeys.js
export const CURRENT_TOKEN = "CURRENT_TOKEN";

export const READ_ALL_ACCOUNTS = "READ_ALL_ACCOUNTS";
export const ADMIN_ACCOUNT_DETAIL = "ADMIN_ACCOUNT_DETAIL";
export const READ_ALL_PRODUCTS = "READ_ALL_PRODUCTS";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const READ_PRODUCT_DETAIL = "READ_PRODUCT_DETAIL";
export const RELATIVE_PRODUCTS = "RELATIVE_PRODUCTS";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const STATISTIC_BRAND = "STATISTIC_BRAND";
export const READ_ALL_VOUCHERS = "READ_ALL_VOUCHERS";
export const READ_VOUCHER = "READ_VOUCHER";
export const SEARCH_VOUCHER = "SEARCH_VOUCHER";
export const READ_ALL_BRANDS = "READ_ALL_BRANDS";
export const READ_ALL_TAGS = "READ_ALL_TAGS";
export const READ_ALL_CATEGORIES = "READ_ALL_CATEGORIES";
export const READ_ALL_CAROUSEL = "READ_ALL_CAROUSEL";
export const READ_ALL_ORDERS = "READ_ALL_ORDERS";
export const READ_ALL_REVIEWS = "READ_ALL_REVIEWS";
export const READ_ALL_SPECIFICATION_KEY = "READ_ALL_REVIEWS";
export const SEARCH_ACCOUNT = "SEARCH_ACCOUNT";
export const ORDER_DETAIL = "ORDER_DETAIL";