---
title: Home Page Detail
---

mindmap
HomePage(HomePage)
    Slider
        NewArrivals(NewArrivals)
        Sales(Sales)
        OnClick{{Go To Product Detail }}
    Carousel
        OnClick{{Go To Product Detail }}
        Popular(Popular)
        FlashSale(FlashSale)
        New(New)
        BestSeller(BestSeller)
    ProductGrid
        SeparateByCategory
            ProductCard
                Name(Name)
                OriginalPrice(OriginalPrice)
                SaledPrice(SaledPrice)
                SalePercent(SalePercent)
                StarPoint(StarPoint)
                OnClick{{Go To Product Detail }}
    SubNavbar
        NavItemsSeparateByCategory
            NavItemsSeparateByBrand/Series
                OnClick{{Go To Filtered Grid Product }}




